### ISSUE TITLE
Bug? Destination Track is Unload Track at Harbor

### ISSUE THREAD

**Issue by AdmiralEllis** [fauxnik/DerailValleyPersistentJobsMod#19]
This is the only mod I have installed. Doing a couple of shunting jobs at Harbor and they all seem to terminate on D7L, the unloading/loading track. Naturally I can't leave them there. I believe this is a bug as they should be taken to Output tracks.

Edit: It seems to be more than just Harbor. Shunting jobs in Food Factory and Town are doing the same thing. Cars are said to be left on the loading/unloading track.

**Comment by RollerKostr** [comment]
> This is the only mod I have installed. Doing a couple of shunting jobs at Harbor and they all seem to terminate on D7L, the unloading/loading track. Naturally I can't leave them there. I believe this is a bug as they should be taken to Output tracks.
> 
> Edit: It seems to be more than just Harbor. Shunting jobs in Food Factory and Town are doing the same thing. Cars are said to be left on the loading/unloading track.

Just encountered exactly this behavior. Seems like it is intentionally forced in Main.cs:484 (latest release, master branch), but idk for what purpose. Cars loaded during shunting jobs should be placed on outbound tracks, like in vanilla game.

**Comment by fauxnik** [comment]
This is working as expected. Car management is left up to the player. This enables otherwise cumbersome logistics such as loading multiple jobs and departing immediately without having to temporarily drop the cars on multiple tracks simply to complete the shunting jobs. Meanwhile, it doesn't preclude the player from storing un/loaded cars on a track of their choosing.
